using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Player {

    public int playerID;        //auto-generated by database
    public string playerName;
    public int ep;              //esteem points
    //public Dictionary<string, Item> 

    public Player(string pPlayerName)
    {
        playerName = pPlayerName;
    }

    

}
